### ISSUE TITLE
Does the docker has API?

### ISSUE THREAD

**Issue by Gavin-Wells** [peasant98/SAM2-Docker#1]

**Comment by peasant98** [comment]
Hi @DoiryCool, so Docker does have a RESTful API you can use: https://docs.docker.com/engine/api/. I am not sure this is recommended though; I think the Docker command line tool (e.g., `docker run`) should take care of your problem.

**Comment by peasant98** [comment]
@DoiryCool following up!

**Comment by Gavin-Wells** [comment]
Okay, I just realized that you're passing the graphical interface. At first, I thought the sam2 API was encapsulated inside the Docker container for external calls.

**Comment by DoiryCool** [comment]
By the way, may I ask if you are in China? Why do you have a Chinese name?

**Comment by Gavin-Wells** [comment]
> @DoiryCool following up!

By the way, may I ask if you are in China? Why do you have a Chinese name?

**Comment by peasant98** [comment]
@DoiryCool I am actually in the USA! I took Chinese in college (and am still taking it) and 司马修 is my Chinese name.
